Repository application-research/estuary, pull requests merged in 2022-12, with the labels that each got.

#614 /keys endpoint
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  handlers.go
Labels: APIv2

#735 Refactored KeyProviderFunc to prevent Memory Leakage
  cmd/estuary-shuttle/init.go
  cmd/estuary-shuttle/main.go
  init.go
Labels: Bug

#817 move metric gauges into their own struct
  cmd/estuary-shuttle/main.go
Labels: Improvement
