Repository application-research/estuary, pull requests merged in 2022-06, with the labels that each got.

#244 Add version v0.1.0
  Makefile
  main.go
Labels: Priority: high

#258 Fix collection inconsistencies on /content/add
  cmd/estuary-shuttle/main.go
  collections.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  handlers.go
Labels: Bug, Documentation

#282 Added client sdk generation script
  scripts/tools/generate-sdk-client
Labels: Documentation, Improvement
