Repository application-research/estuary, pull requests merged in 2022-07, with the labels that each got.

#297 Bump filclient version (fix remote addr bug)
  go.mod
  go.sum
Labels: Bug

#329 change name variables to filename
  cmd/estuary-shuttle/main.go
  dbmgr/dbmgr.go
  dbmgr/dbmgr_test.go
  handlers.go
  main.go
  pinning.go
  replication.go
  util/content.go
Labels: Documentation, Refactor

#373 Added better error handling with empty content-length header
  cmd/estuary-shuttle/main.go
  cmd/estuary-shuttle/retrieval.go
  cmd/estuary-shuttle/rpc.go
  handlers.go
  main.go
  offloading.go
  pinning.go
  ranking.go
  replication.go
  retrieval.go
  shuttle.go
  util/http.go
  util/misc.go
Labels: Improvement

#159 Autoretrieve/Indexer Integration
  autoretrieve/autoretrieve.go
  autoretrieve/engine.go
  autoretrieve/linksystem.go
  autoretrieve/options.go
  config/estuary.go
  config/node.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  export.go
  gc.go
  go.mod
  go.sum
  handlers.go
  init.go
  main.go
  node/node.go
  offloading.go
  pinning.go
  replication.go
  retrieval.go
  shuttle.go
  trackbs.go
  util/car.go
  util/car_test.go
  util/content.go
  util/retrieval.go
  util/shuttle.go
Labels: New Feature, Priority: high
