Repository application-research/estuary, pull requests merged in 2022-08, with the labels that each got.

#371 Fix redirect on content adding
  handlers.go
  main.go
  replication.go
  shuttle.go
  util/misc.go
Labels: Bug

#381 Constants package
  autoretrieve/autoretrieve.go
  autoretrieve/engine.go
  cmd/estuary-shuttle/main.go
  constants/autoretrieve.go
  constants/constants.go
  handlers.go
  main.go
  offloading.go
  pinning.go
  replication.go
  util/content.go
Labels: Priority: low, Improvement

#406 fix: application crashing on unverified client datacap
  replication.go
Labels: Bug, Priority: medium
