Repository application-research/estuary, pull requests merged in 2022-11, with the labels that each got.

#515 Fix collections add content
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  handlers.go
Labels: API

#550 Fix /user/stats swagger annotations
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  handlers.go
Labels: Documentation, API

#551 Annotate invites api
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  handlers.go
Labels: Documentation, API

#443 Ignore trailing slash on API endpoints
  cmd/estuary-shuttle/main.go
  handlers.go
Labels: Question

#588 /buckets (collections v2)
  buckets/buckets.go
  cmd/estuary-shuttle/main.go
  collections/collections.go
  contentmgr/gc.go
  contentmgr/offloading.go
  contentmgr/pinning.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  handlers.go
  main.go
  pinning.go
  scripts/samples/add-file-to-collection.sh
  tests/chaos/README.md
  tests/chaos/add-content-with-expired-apikey.sh
  tests/regression/README.md
  tests/regression/add-content-collection.sh
  tests/regression/add-content.sh
  tests/regression/add-file.sh
  tests/regression/create-collection.sh
  tests/regression/list-collections.sh
  util/auth.go
  util/auth_test.go
  util/content.go
  util/shuttle.go
Labels: APIv2

#520 Fix minor swagger inconsistencies
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  handlers.go
  pinning.go
Labels: Documentation
